### ISSUE TITLE
Add mention to current duty employee in forward message 

### ISSUE THREAD

**Issue by tolmachev-pravo** [deimosowen/Mattermost_CaseOneBot#11]
Необходимо добавить макрос, который позволяет для текущего канала вставлять mention на текущего дежурного в рамках канала.
Если текущего дежурного нет, то макрос заполняется пустым значением.
Также хорошо бы прописать где-то доступные макросы.

**Comment by deimosowen** [comment]
@tolmachev-pravo 
Я правильно поднимаю, что ты хочешь иметь возможность указывать команду, типа:
`!forward; [id] ; [id]; Поступило новое сообщение из канала ~{channel_display_name} от {sender_name}.
{current_duty_mention}, пожалуйста, обрати внимание на это [сообщение]({post_link})`

**Comment by tolmachev-pravo** [comment]
Например, да
