### ISSUE TITLE
Add the ability to change the description of a logged event

### ISSUE THREAD

**Issue by DaniilYashkin** [deimosowen/Mattermost_CaseOneBot#61]
📌 **Current Behavior:** 
At the moment, the description is taken from the Google calendar event and when logging the event, it ends up in a task with the specified name

🎯 **Desired Behavior:** 
I would like to be able to change the name of the event, since it is usually quite short and does not fully reflect the essence of the event

Thanks for understanding♥

**Comment by deimosowen** [comment]
Done
